---
title: "thesis_prep"
author: "Daniel Shapiro"
date: "3/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(readxl)
library(gt)
library(lubridate)
library(mudata2)
```

## Table 1

```{r table_1}
x <- read_xlsx("raw-data/table.xlsx") %>%
  rename('American Contacts' = 'Contact with Americans?') %>%
  gt() %>%
  tab_header(title = "Participant Profiles",
             subtitle = "(All names are pseudonyms)") %>%
  tab_footnote(footnote = "Aleksandr is listed as N/A for 'American Contacts' because he did not volunteer an answer for the question.", locations = cells_column_labels(
      columns = vars('American Contacts')))

x
```

## Graph 1

```{r graph_1}
y <- read_xlsx("raw-data/VTsIOM.xlsx") %>%
  rename('Year' = '...1')

plot2 <- ggplot(y, aes(x = Year, y = Negative)) +
  geom_line(color = "red") +
  labs(title = "Percentage of Russians that Perceive the U.S.-Russian Relationship as Negative",
       subtitle = "Data from VTsIOM, 2016-2019",
       x = "Year",
       y = "Percentage") +
  geom_text(aes(label = Negative), hjust = 1, vjust= 1) +
  expand_limits(y = 0)

plot2

ggsave("plot2.png")
```

## Graph 2

```{r graph_2}
x <- read_xlsx("raw-data/Russus.xlsx")

x2 <- pivot_longer(x, everything()) %>%
  group_by(name) %>%
  head(160) %>%
  rename(
    Good = value
  )

x3 <- pivot_longer(x, everything()) %>%
  group_by(name) %>%
  tail(160) %>%
  rename(
    Bad = value
  )

x4 = merge(x2, x3, by = "name")

x4$name <- as.numeric(as.character(x4$name))
x4 <- x4[-c(1, 2, 3, 4), ]

plot <- ggplot(x4, aes(x = name)) +
  geom_line(aes(y = Good, colour = "Positive")) +
  geom_line(aes(y = Bad, colour = "Negative")) +
  labs(title = "How Russians Perceive the United States",
       subtitle = "Data from Levada Center polls, 1997-2019",
       x = "Year",
       y = "Percentage",
       colour = "Relationship")
  

plot

ggsave("plot.png", width = 12, height = 5)

```

## Graph 3

```{r graph_3}
z <- read_xlsx("raw-data/2019dat.xlsx")

plot3 <- ggplot(z, aes(x = Connection, y = Percent)) +
  geom_col(aes(fill = Change), position = "dodge") +
  labs(x = "Type of Connection",
       title = "Russian Opinion Poll: What Should be Done About Connections with the U.S.?",
       subtitle = "Data from 2019 VTsIOM polling")

plot3

ggsave("plot3.png")
```

## Graph 4

```{r graph_4}
y <- read_xlsx("raw-data/Usruss.xlsx") %>%
  rename(
    Date = ...1
  )

y2 <- y %>%
  mutate(Favorable = rowSums(y[,c("Very favorable", "Mostly favorable")])) %>%
  mutate(Unfavorable = rowSums(y[,c("Mostly unfavorable", "Very unfavorable")])) %>%
  select(Date, Favorable, Unfavorable)

y2$Date <- substr(y2$Date, 0, 8)

y2$Date <- parse_date_time(y2$Date, orders = "ym0")

gg <- ggplot(y2, aes(x = Date)) + 
  geom_line(aes(y = Favorable, colour = "Positive")) +
  geom_line(aes(y = Unfavorable, colour = "Negative")) +
  labs(title = "How Americans Perceive Russia",
       subtitle = "Data from Gallup polls, 1997-2019",
       x = "Year",
       y = "Percentage",
       colour = "Relationship")

gg

ggsave("gg.png", width = 12, height = 5)
```

## Graph 5

```{r graph_5}
A <- read_excel("raw-data/Fields.xlsx")

ggplot(A, aes(x = reorder(Category, Number), y = Number)) +
         geom_col(fill = "#FF6666") +
  xlab("Area") +
  labs(title = "Most Popular Responses") +
  coord_flip()

ggsave("Fields.png")
  
```